#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /api/login
    methods: ['POST']

api_refresh_token:
    path: /api/token/refresh

api_token_invalidate:
    path: /api/token/invalidate